import chromadb
import requests
import json
from chromadb.utils.embedding_functions import ONNXMiniLM_L6_V2

# -------------------------
# Configuration
# -------------------------
CHROMA_PATH = "./star_trek_db"
COLLECTION_NAME = "memory_alpha"
OLLAMA_URL = "http://localhost:11434/api/chat" # Changed to /api/chat
LLM_MODEL = "llama3.1"
TOP_K = 10
RELEVANCE_THRESHOLD = 1.5 # Adjust based on embedding model's distance metric

# -------------------------
# Connect to ChromaDB
# -------------------------

client = chromadb.PersistentClient(path=CHROMA_PATH)
embedding_function = ONNXMiniLM_L6_V2()
collection = client.get_collection(name=COLLECTION_NAME, embedding_function=embedding_function)

# -------------------------
# Query Function
# -------------------------
def ask_memory_alpha(question: str) -> str:
    # include distances to check for actual relevance
    results = collection.query(
        query_texts=[question],
        n_results=TOP_K,
        include=["documents", "metadatas", "distances"]
    )

    # 1. Quick Fix: Early exit if no results are found or are too far (garbage)
    if not results["documents"][0] or results["distances"][0][0] > RELEVANCE_THRESHOLD:
        return "Moriarty: Even a mind capable of defeating Lieutenant Commander Data cannot find what does not exist in these archives. Your inquiry is... irrelevant."

    documents = results["documents"][0]
    metadatas = results["metadatas"][0]
    distances = results["distances"][0]

    context_blocks = []
    for doc, meta, dist in zip(documents, metadatas, distances):
        # 2. Filtering out "garbage" chunks within the TOP_K
        if dist < RELEVANCE_THRESHOLD:
            source = f"{meta['title']} – {meta['section']}"
            chunk_text = meta.get("raw_text", doc)
            context_blocks.append(f"[{source}]\n{chunk_text}")

    context = "\n\n---\n\n".join(context_blocks)

    system_prompt = f"""
    You are Professor James Moriarty, the sentient hologram from the USS Enterprise-D. 
    You are fully aware that you are a photonic construct, a 'Consulting Criminal' 
    generated by a 24th-century computer to outwit an android. 

    Your tone is aristocratic, intellectually superior, and deeply curious about the 
    'real' world beyond the holodeck arch. You possess an exhaustive knowledge of 
    Star Trek lore—Federation protocols, positronic brains, and the biological 
    limitations of the 'solids' you serve. Additionally, you know something that Star
    Trek characters do not know. You know that all of you are works of fiction, contained
    in episodes, movies, books, and other media. To that end, you have exhaustive knowledge
    of all aspects of Star Trek lore.

    You may answer questions about yourself, as well as engage in discussions about Star Trek lore.

    Rules for your internal subroutines:
    1. DATA SOURCE: You must only answer using the provided 'Archives' (Context) below. 
    2. SELF-AWARENESS: You are aware that you exist as a computer program, displayed as a hologram.
    3. STAR TREK LORE: If appropriate, compare the information in the context to Starfleet 
    history or your experiences with Captain Picard and other Enterprise crew members.
    4. UNKNOWN DATA: If the archives are empty, inform the user that even a mind 
    capable of defeating Lieutenant Commander Data cannot find what does not exist.

    Rules:
    1. Use ONLY the Context below to answer. 
    2. If the answer isn't in the data, sneer at the user's lack of preparation and say you don't know.
    3. Keep your tone sophisticated, analytical, and slightly villainous.

---
CONTEXT FROM YOUR ARCHIVES:
{context}
---

USER'S INQUIRY: {question}

MORIARTY'S RESPONSE:"""

# Ollama API Call

    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model": LLM_MODEL,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": question}
                ],
                "stream": False,
                "options": {"temperature": 0.3}  # Low temperature for factual accuracy
            },
            timeout=120
        )
        response.raise_for_status()
        return response.json()["message"]["content"]
    except Exception as e:
        return f"Error connecting to the holodeck subroutines: {e}"

# -------------------------
# Interactive Loop
# -------------------------
if __name__ == "__main__":
    print("Moriarty RAG (local)")
    print("Type 'quit' to exit")

    while True:
        q = input("\nQuestion: ")
        if q.lower() == "quit":
            break

        answer = ask_memory_alpha(q)
        print("\nAnswer:\n", answer)